let toyStorys = [
  {
    id: 1,
    nome: "Woody",
    tipo: "Boneco",
    anoFabricacao: 1995,
    cor: "Marrom",
    quantidadeEstoque: 50,
  },
  {
    id: 2,
    nome: "Buzz Lightyear",
    tipo: "Boneco de Ação",
    anoFabricacao: 1995,
    cor: "Branco",
    quantidadeEstoque: 45,
  },
  {
    id: 3,
    nome: "Jessie",
    tipo: "Boneca",
    anoFabricacao: 1999,
    cor: "Amarelo",
    quantidadeEstoque: 30,
  },
  {
    id: 4,
    nome: "Sr. Cabeça de Batata",
    tipo: "Brinquedo Montável",
    anoFabricacao: 1992,
    cor: "Marrom",
    quantidadeEstoque: 40,
  },
  {
    id: 5,
    nome: "Rex",
    tipo: "Dinossauro",
    anoFabricacao: 1995,
    cor: "Verde",
    quantidadeEstoque: 25,
  },
  {
    id: 6,
    nome: "Slinky",
    tipo: "Cachorro de Mola",
    anoFabricacao: 1995,
    cor: "Marrom",
    quantidadeEstoque: 35,
  },
  {
    id: 7,
    nome: "Bo Peep",
    tipo: "Boneca",
    anoFabricacao: 1995,
    cor: "Rosa",
    quantidadeEstoque: 20,
  },
  {
    id: 8,
    nome: "Hamm",
    tipo: "Porquinho Mealheiro",
    anoFabricacao: 1995,
    cor: "Rosa",
    quantidadeEstoque: 55,
  },
  {
    id: 9,
    nome: "Aliens (Homens Verdes)",
    tipo: "Brinquedo",
    anoFabricacao: 1995,
    cor: "Verde",
    quantidadeEstoque: 100,
  },
  {
    id: 10,
    nome: "Bala no Alvo",
    tipo: "Boneca de Puxar",
    anoFabricacao: 1999,
    cor: "Branco",
    quantidadeEstoque: 15,
  },
  {
    id: 11,
    nome: "Lotso Huggin' Bear",
    tipo: "Urso de Pelúcia",
    anoFabricacao: 2010,
    cor: "Rosa",
    quantidadeEstoque: 10,
  },
  {
    id: 12,
    nome: "Forky",
    tipo: "Artesanato",
    anoFabricacao: 2019,
    cor: "Branco",
    quantidadeEstoque: 22,
  },
];

export default { toyStorys };
